module.exports = {
    en: {
        'captcha-check-failed': 'Oops! It looks like there was an error with the reCAPTCHA verification.',
        'code-expired': 'The verification code sent via SMS has expired. Please request a new verification code to try again.',
        'email-change-needs-verification': "For security reasons, you must have a verified email if you're using multi-factor authentication.",
        'email-already-in-use': 'The email address you provided is already associated with another account.',
        'expired-action-code': 'The action code has expired and can no longer be used. Please request a new one.',
        'cancelled-popup-request': 'Another popup is conflicting with the current operation, so we had to cancel it. Please try again.',
        'invalid-verification-code':
            'The SMS verification code you entered is incorrect. Please request a new one and make sure to use the correct code.',
        'invalid-email': 'The email address you provided is not in the correct format. Please check and try again.',
        'invalid-action-code': 'The action code you provided is invalid. This could be due to (a formatting issue, expiration, or previous use).',
        'wrong-password': 'Oops! The password you entered is invalid. Please double-check it and try again.',
        'invalid-phone-number': 'The phone number you provided is not in the correct format. Please check and try again.',
        'missing-phone-number': 'A phone number is required to send verification codes.',
        'account-exists-with-different-credential':
            'An account with the same email address but different sign-in credentials already exists. Please sign in using the appropriate provider for this email address.',
        'network-request-failed': 'Oops! A network error (such as a timeout, interrupted connection, or unreachable host) has occurred.',
        'popup-closed-by-user': 'The popup has been closed by you before finalizing the operation.',
        'provider-already-linked': 'You can only be linked to one account for the given provider.',
        'redirect-cancelled-by-user': 'You canceled the redirect operation before it could be completed.',
        'redirect-operation-pending': 'A redirect sign-in operation is already in progress.',
        timeout: 'Oops! The operation has timed out.',
        'user-cancelled': 'You did not grant your application the permissions it requested.',
        'user-not-found': 'Oops! There is no user record corresponding to this identifier. The user may have been deleted.',
        'user-disabled': 'The user account has been disabled by an administrator.',
        'user-mismatch': 'The credentials you provided do not match the previously signed-in user.',
        'weak-password': 'The password must be at least 6 characters long.',
        'web-storage-unsupported': 'Oops! This browser is not supported, or third-party cookies and data may be disabled.',
        'unverified-email': 'Please verify your e-mail before signing in.',
        'phone-not-exist': 'There is no account associated with this phone number.',
    },

    hy: {
        'captcha-check-failed': 'Սխալ առաջացավ reCAPTCHA հաստատման հետ:',
        'code-expired': 'SMS-ով ուղարկված հաստատման կոդի ժամկետն անցել է: Խնդրում ենք նոր հաստատման կոդ պահանջել՝ նորից փորձելու համար:',
        'email-change-needs-verification':
            'Անվտանգության նկատառումներով, դուք պետք է ունենաք հաստատված էլ. փոստ եթե օգտագործում եք բազմագործոն նույնականացում:',
        'email-already-in-use': 'Ձեր տրամադրած էլ. փոստի հասցեն արդեն կապված է ուրիշ այլ հաշվի հետ:',
        'expired-action-code': 'Action կոդը ժամկետանց է և այլևս հնարավոր չէ օգտագործել: Խնդրում ենք նորը պահանջել:',
        'cancelled-popup-request':
            'Ուրիշ այլ թռուցիկ պատուհան հակասում է ընթացիկ գործողությանը, դրա պատճառով մենք գործողությանը չեղարկել ենք: Խնդրում ենք նորից փորձել:',
        'invalid-verification-code':
            'Ձեր մուտքագրած SMS հաստատման կոդը սխալ է: Խնդրում ենք նորը պահանջել և վստահ լինեք, որ ճիշտ կոդն եք մուտքագրում:',
        'invalid-email': 'Ձեր տրամադրած էլ. փոստի հասցեն ճիշտ ձևաչափով չէ: Խնդրում ենք ստուգեք և նորից փորձել:',
        'invalid-action-code': 'Ձեր տրամադրած action կոդը անվավեր է: Պատճառը կարող է լինել (ձևաչափման խնդիր, ժամկետի ավարտ, կամ նախկին օգտագործում):',
        'wrong-password': 'Ձեր մուտքագրած գաղտնաբառը անվավեր է: Խնդրում ենք կրկնակի ստուգեք և նորից փորձել:',
        'invalid-phone-number': 'Ձեր տրամադրած հեռ. համարը ճիշտ ձևաչափով չէ: Խնդրում ենք ստուգեք և նորից փորձել:',
        'missing-phone-number': 'Հաստատման կոդեր ուղարկելու համար անհրաժեշտ է հեռ. համար:',
        'account-exists-with-different-credential':
            'Նույն էլ. փոստի հասցեով, բայց մուտքի տարբեր հավատարմագրերով հաշիվ արդեն կա: Խնդրում ենք մուտք գործեք՝ օգտագործելով այս էլ. փոստի հասցեի համապատասխան մատակարարը:',
        'network-request-failed': 'Ցանցի սխալ է տեղի ունեցել: Պատճառը կարող է լինել (ժամանակը սպառվել է, ընդհատված կապ, կամ անհասանելի հոսթ):',
        'popup-closed-by-user': 'Թռուցիկ պատուհանը փակվել է ձեր կողմից՝ նախքան գործողությունը վերջնականացնելը:',
        'provider-already-linked': 'Դուք կարող եք կապվել տվյալ մատակարարի միայն մեկ հաշվի հետ:',
        'redirect-cancelled-by-user': 'Դուք չեղարկել եք վերահղման գործողությունը՝ նախքան այն ավարտվելը:',
        'redirect-operation-pending': 'Մուտքի վերահղման գործողությունն արդեն ընթացքի մեջ է:',
        timeout: 'Գործողության ժամանակը սպառվել է:',
        'user-cancelled': 'Դուք չեք տրամադրել ձեր դիմումին նրա պահանջած թույլտվությունները:',
        'user-not-found': 'Այս նույնացուցիչին համապատասխան օգտվողի գրառում չկա: Հնարավոր է՝ օգտատերը ջնջված է:',
        'user-disabled': 'Օգտատիրոջ հաշիվն անջատվել է ադմինիստրատորի կողմից:',
        'user-mismatch': 'Ձեր տրամադրած հավատարմագրերը չեն համապատասխանում նախկինում մուտք գործած օգտատիրոջ հետ:',
        'weak-password': 'Գաղտնաբառը պետք է լինի առնվազն 6 նիշ:',
        'web-storage-unsupported': 'Այս դիտարկիչը չի աջակցվում, կամ երրորդ կողմի cookie-ներն ու տվյալները կարող են անջատված լինել:',
        'unverified-email': 'Խնդրում ենք հաստատել ձեր էլ. փոստը նախքան մուտք գործելը:',
        'phone-not-exist': 'Այս հեռախոսահամարի հետ կապված հաշիվ չկա:',
    },
};